### ISSUE TITLE
add event handling support for this module

### ISSUE THREAD

**Issue by MNA4** [Abdur-rahmaanJ/hooman#115]
currently this module is unable to handle events such as detecting mousedown, mouseup, etc.
I propose to implement event handling by using python decorators.
an example of how it might work:
```py
@hapi.onmousedown
def onmousedown(mouseX, mouseY):
    print("mouse pressed at:", mouseX + ', ' + 'mouseY)
```

**Comment by MNA4** [comment]
#116

**Comment by Abdur-rahmaanJ** [comment]
@MNA4 Thanks a ton! Mind updating the README?
