### ISSUE TITLE
Add more demo

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/hooman#15]
Add more cool demos using the Hooman API

mail me : arj.python@gmail.com if you are unsure of the issue

first timers only

**Comment by SatvikR** [comment]
Would a pong game work for this?

**Comment by Abdur-rahmaanJ** [comment]
Absolutely yes!

**Comment by reddybhargava** [comment]
I've added a falling stars demo.
Take a look at it and let me know if you need any changes.

**Comment by Abdur-rahmaanJ** [comment]
@reddybhargava Thanks! Merged! Could you just update the readme by having a section for contributing demos? Basically add that you have to include your name and github url in the file docstring? Thanks!

**Comment by reddybhargava** [comment]
@Abdur-rahmaanJ Done!

**Comment by Abdur-rahmaanJ** [comment]
@reddybhargava Great! You have Twitter btw?

**Comment by reddybhargava** [comment]
Yup. @reddybhargava99 is my Twitter handle.
