### ISSUE TITLE
Add default framerate=25 argument to save_record

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/hooman#34]
Add default argument `framerate=25` [here](https://github.com/Abdur-rahmaanJ/hooman/blob/284176682e9363ca8794a2f38f1dea79a760a2bd/hooman/hooman.py#L659)

**Comment by divyakelaskar** [comment]
I would like to work on this.

**Comment by Nakadie** [comment]
It looks like this was completed?

**Comment by TheBigKahuna353** [comment]
Whoops, forgot to close. Thanks bro
