### ISSUE TITLE
Add calculator demo

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/hooman#50]
Add a calculator demo to this folder https://github.com/Abdur-rahmaanJ/hooman/tree/master/hooman/demos

**Comment by Hamaad7865** [comment]
I'll take it

**Comment by Abdur-rahmaanJ** [comment]
@Hamaad7865 Btw you can try an on-cloud ide?

**Comment by SahajaThota** [comment]
Hi @Abdur-rahmaanJ ,
It's really fun working on calculator demo. I have added it to the hooman/demos folder. Can you please review and merge it. PR-https://github.com/Abdur-rahmaanJ/hooman/pull/68

**Comment by chandana1221** [comment]
Hi @Abdur-rahmaanJ ,
The calculatordemo is a lot of fun to work on. It is now a part of the hooman/demo subdirectory. Would you kindly review and combine it.
PR- https://github.com/Abdur-rahmaanJ/hooman/pull/67

**Comment by bharathchittamuru7** [comment]
Hi @Abdur-rahmaanJ ,
I enjoyed working on the Calculator_Demo and I have added it to hooman/demos folder. Can you please review and merge it.
PR - https://github.com/Abdur-rahmaanJ/hooman/pull/72

Thanks,
Bharath C

**Comment by bharathchittamuru7** [comment]
Hi @Abdur-rahmaanJ 
I enjoyed working on the Calculator_Demo and I have added it to hooman/demos folder. Can you please review and merge it.
PR - https://github.com/Abdur-rahmaanJ/hooman/pull/74

Thanks,
Bharath C
