### ISSUE TITLE
Fix download badge not appearing

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/hooman#51]
File: 

https://github.com/Abdur-rahmaanJ/hooman/blob/master/README.md

![Selection_090](https://github.com/Abdur-rahmaanJ/hooman/assets/22630684/df305c16-52f0-4d1c-a0c6-f008b851fdeb)

expected

![Selection_091](https://github.com/Abdur-rahmaanJ/hooman/assets/22630684/c03c8e2f-4922-4011-947d-22c4355a8058)

How to fix?

## Copy the badge at

https://www.pepy.tech/projects/hooman

**Comment by Hamaad7865** [comment]
I'll take it

**Comment by Abdur-rahmaanJ** [comment]
Issue solved by #52
